# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf64ae6b05d9ac2b04c7f74839b71623"
name = "scribe-ai"
handle = "scribe-ai"
application_url = "https://hamburg-desktop-perfect-philips.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "scribe-ai.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://hamburg-desktop-perfect-philips.trycloudflare.com/auth/callback",
  "https://hamburg-desktop-perfect-philips.trycloudflare.com/auth/shopify/callback",
  "https://hamburg-desktop-perfect-philips.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
